import type { ProcurementDb } from "@/lib/os/procurement/types";
import { createDefaultBranches } from "@/lib/os/branches";
import { defaultNotificationPreferences } from "@/lib/os/branches/migrate-branches";
import { defaultFlipOfficeSettings } from "@/lib/os/integrations/flip-office/defaults";

export function createSeedDb(): ProcurementDb {
  const now = new Date().toISOString();
  const today = new Date().toISOString().slice(0, 10);
  const branches = createDefaultBranches(now);

  const vendors = [
    {
      id: "vnd_amul",
      name: "Amul Dairy",
      gstNumber: "24AABCA1234F1Z5",
      panNumber: "AABCA1234F",
      phone: "+91 98765 43210",
      address: "Anand, Gujarat",
      email: "accounts@amul.co.in",
      contactPerson: "Rajesh Patel",
      paymentTermsDays: 15,
      invoicePattern: "AMUL-INV-*",
      category: "Food Supplier" as const,
      status: "active" as const,
      createdAt: now,
    },
    {
      id: "vnd_fresh",
      name: "Fresh Farms Vegetables",
      gstNumber: "27AABCF5678G1Z2",
      panNumber: "AABCF5678G",
      phone: "+91 91234 56789",
      address: "Pune, Maharashtra",
      email: null,
      contactPerson: "Suresh Kulkarni",
      paymentTermsDays: 7,
      invoicePattern: "FF-*",
      category: "Food Supplier" as const,
      status: "active" as const,
      createdAt: now,
    },
  ];

  const inventoryItems = [
    {
      id: "itm_mozzarella",
      name: "Cheese Mozzarella",
      category: "Dairy" as const,
      unit: "kg",
      currentStock: 32,
      parLevel: 20,
      status: "active" as const,
      createdAt: now,
    },
    {
      id: "itm_paneer",
      name: "Paneer",
      category: "Dairy" as const,
      unit: "kg",
      currentStock: 18,
      parLevel: 15,
      status: "active" as const,
      createdAt: now,
    },
    {
      id: "itm_tomato",
      name: "Tomato",
      category: "Vegetables" as const,
      unit: "kg",
      currentStock: 8,
      parLevel: 12,
      status: "active" as const,
      createdAt: now,
    },
  ];

  return {
    branches,
    vendors,
    purchaseBills: [],
    inventoryItems,
    inventoryMovements: [],
    openingStock: inventoryItems.map((item) => ({
      id: `opn_${item.id}`,
      itemId: item.id,
      date: today,
      quantity: item.currentStock,
      source: "manual" as const,
    })),
    closingStock: [],
    omissionCases: [],
    creditNotes: [],
    internalAdjustments: [],
    vendorLedger: [],
    categories: [
      { id: "cat_dairy", name: "Dairy" },
      { id: "cat_veg", name: "Vegetables" },
      { id: "cat_dry", name: "Dry Store" },
      { id: "cat_spice", name: "Spices" },
      { id: "cat_sauce", name: "Sauces" },
      { id: "cat_imp", name: "Imported Foods" },
      { id: "cat_can", name: "Canned Goods" },
      { id: "cat_pack", name: "Packaging" },
      { id: "cat_bev", name: "Beverages" },
      { id: "cat_clean", name: "Cleaning" },
      { id: "cat_cons", name: "Consumables" },
      { id: "cat_prep", name: "Kitchen Prep" },
    ],
    itemAliases: [
      {
        id: "als_mozz",
        itemId: "itm_mozzarella",
        alias: "Mozzarella Cheese",
        vendorId: "vnd_amul",
        createdAt: now,
      },
      {
        id: "als_paneer",
        itemId: "itm_paneer",
        alias: "Paneer Full Fat",
        vendorId: "vnd_amul",
        createdAt: now,
      },
    ],
    unitConversions: [
      {
        id: "ucv_paneer_g",
        itemId: "itm_paneer",
        fromUnit: "g",
        toUnit: "kg",
        factor: 0.001,
      },
      {
        id: "ucv_mozz_g",
        itemId: "itm_mozzarella",
        fromUnit: "g",
        toUnit: "kg",
        factor: 0.001,
      },
    ],
    grns: [],
    categoryMappings: [],
    billRevisions: [],
    auditLog: [],
    billEditHistory: [],
    vendorDisputes: [],
    creditRecoveries: [],
    recoveryActivities: [],
    vendorDocuments: [],
    disputeNotes: [],
    recipes: [
      {
        id: "rcp_margherita",
        branchId: "br_prahladnagar",
        name: "Margherita Pizza",
        sellingPrice: 399,
        yield: 1,
        yieldUnit: "portion",
        status: "active",
        outlet: "Table Tales",
        createdAt: now,
      },
      {
        id: "rcp_paneer_tikka",
        branchId: "br_prahladnagar",
        name: "Paneer Tikka",
        sellingPrice: 349,
        yield: 1,
        yieldUnit: "portion",
        status: "active",
        outlet: "Table Tales",
        createdAt: now,
      },
    ],
    recipeIngredients: [
      {
        id: "ing_mozz",
        recipeId: "rcp_margherita",
        itemId: "itm_mozzarella",
        itemName: "Cheese Mozzarella",
        quantity: 0.12,
        unit: "kg",
      },
      {
        id: "ing_tom",
        recipeId: "rcp_margherita",
        itemId: "itm_tomato",
        itemName: "Tomato",
        quantity: 0.08,
        unit: "kg",
      },
      {
        id: "ing_paneer",
        recipeId: "rcp_paneer_tikka",
        itemId: "itm_paneer",
        itemName: "Paneer",
        quantity: 0.18,
        unit: "kg",
      },
    ],
    prepRecipes: [
      {
        id: "prep_pizza_sauce",
        name: "Pizza Sauce",
        outputItemId: null,
        outputItemName: "Pizza Sauce",
        outputYield: 5,
        outputUnit: "kg",
        status: "active",
        createdAt: now,
      },
      {
        id: "prep_garlic_butter",
        name: "Garlic Butter",
        outputItemId: null,
        outputItemName: "Garlic Butter",
        outputYield: 2,
        outputUnit: "kg",
        status: "active",
        createdAt: now,
      },
    ],
    prepIngredients: [
      {
        id: "pi_tom",
        prepRecipeId: "prep_pizza_sauce",
        itemId: "itm_tomato",
        itemName: "Tomato",
        quantity: 4.5,
        unit: "kg",
      },
    ],
    productionBatches: [],
    sales: [],
    vendorPayments: [],
    stockVariances: [],
    employees: [
      {
        id: "emp_chef_01",
        branchId: "br_prahladnagar",
        flipOfficeId: "FO-CHEF-01",
        employeeCode: "TT-K001",
        name: "Amit Sharma",
        department: "kitchen",
        designation: "Head Chef",
        outlet: "Table Tales",
        phone: "+91 98111 00001",
        email: "amit@tabletales.in",
        dateOfJoining: "2024-03-01",
        monthlySalary: 45000,
        hourlyRate: 250,
        status: "active",
        createdAt: now,
      },
      {
        id: "emp_srv_01",
        branchId: "br_sbr",
        flipOfficeId: "FO-SRV-01",
        employeeCode: "TT-S001",
        name: "Priya Nair",
        department: "service",
        designation: "Floor Manager",
        outlet: "Table Tales",
        phone: "+91 98111 00002",
        email: null,
        dateOfJoining: "2024-06-15",
        monthlySalary: 32000,
        hourlyRate: 180,
        status: "active",
        createdAt: now,
      },
      {
        id: "emp_ck_01",
        branchId: "br_central_kitchen",
        flipOfficeId: "FO-CK-01",
        employeeCode: "PF-CK001",
        name: "Ravi Kumar",
        department: "central_kitchen",
        designation: "Prep Cook",
        outlet: "Pure Foods Central Kitchen",
        phone: null,
        email: null,
        dateOfJoining: "2025-01-10",
        monthlySalary: 28000,
        hourlyRate: 160,
        status: "active",
        createdAt: now,
      },
    ],
    attendanceRecords: [],
    payrollRuns: [],
    payrollLines: [],
    operatingExpenses: [
      {
        id: "exp_rent_01",
        branchId: "br_prahladnagar",
        date: today,
        month: today.slice(0, 7),
        category: "Rent",
        vendorName: "Landlord",
        description: "Outlet rent",
        amountPaise: 8_500_000,
        outlet: "Table Tales Prahladnagar",
        attachmentUrl: null,
        status: "approved",
        isRecurring: true,
        recurrence: "monthly",
        createdBy: "accountant",
        approvedBy: "owner",
        approvedAt: now,
        createdAt: now,
        auditLog: [{ action: "seed", at: now, by: "system" }],
      },
      {
        id: "exp_util_01",
        branchId: "br_prahladnagar",
        date: today,
        month: today.slice(0, 7),
        category: "Electricity",
        vendorName: "Torrent Power",
        description: "Electricity",
        amountPaise: 2_200_000,
        outlet: "Table Tales Prahladnagar",
        attachmentUrl: null,
        status: "approved",
        isRecurring: true,
        recurrence: "monthly",
        createdBy: "accountant",
        approvedBy: "owner",
        approvedAt: now,
        createdAt: now,
        auditLog: [{ action: "seed", at: now, by: "system" }],
      },
    ],
    flipOfficeSyncLogs: [],
    flipOfficeSettings: defaultFlipOfficeSettings(),
    flipSales: [],
    flipSaleItems: [],
    flipCustomers: [],
    flipMenuMappings: [],
    approvalRequests: [],
    notifications: [],
    notificationPreferences: defaultNotificationPreferences(),
    vaultDocuments: [],
    dailyMisReports: [],
    menuIngredients: [],
    menuRecipeIngredients: [],
    recipeCostSettings: [],
    recipeCostSnapshots: [],
  };
}
