import type { MenuIngredient, MenuIngredientCategory } from "@/lib/os/procurement/types";

type SeedRow = [string, MenuIngredientCategory, string];

const SEED_ROWS: SeedRow[] = [
  ["Paneer", "Dairy", "kg"],
  ["Mozzarella Cheese", "Dairy", "kg"],
  ["Cream Cheese", "Dairy", "kg"],
  ["Fresh Cream", "Dairy", "litre"],
  ["Butter", "Dairy", "kg"],
  ["Curd / Hung Curd", "Dairy", "kg"],
  ["Milk", "Dairy", "litre"],
  ["Parmesan Cheese", "Dairy", "kg"],
  ["Ice Cream", "Dairy", "litre"],
  ["Whipped Cream", "Dairy", "litre"],
  ["Tomato", "Vegetables", "kg"],
  ["Onion", "Vegetables", "kg"],
  ["Capsicum Red", "Vegetables", "kg"],
  ["Capsicum Yellow", "Vegetables", "kg"],
  ["Capsicum Green", "Vegetables", "kg"],
  ["Zucchini", "Vegetables", "kg"],
  ["Broccoli", "Vegetables", "kg"],
  ["Mushroom", "Vegetables", "kg"],
  ["Baby Corn", "Vegetables", "kg"],
  ["Carrot", "Vegetables", "kg"],
  ["Spinach", "Vegetables", "kg"],
  ["Cucumber", "Vegetables", "kg"],
  ["Avocado", "Vegetables", "kg"],
  ["Lettuce", "Vegetables", "kg"],
  ["Methi", "Vegetables", "kg"],
  ["Bok Choi", "Vegetables", "kg"],
  ["Water Chestnut", "Vegetables", "kg"],
  ["Spring Onion", "Vegetables", "kg"],
  ["Jalapenos (pickled)", "Vegetables", "kg"],
  ["Corn (sweet corn)", "Vegetables", "kg"],
  ["Potato", "Vegetables", "kg"],
  ["Cauliflower", "Vegetables", "kg"],
  ["Green Beans", "Vegetables", "kg"],
  ["Peas", "Vegetables", "kg"],
  ["Cherry Tomatoes", "Vegetables", "kg"],
  ["Tofu", "Vegetables", "kg"],
  ["Basmati Rice", "DryStore", "kg"],
  ["Jasmine Rice", "DryStore", "kg"],
  ["Penne Pasta", "DryStore", "kg"],
  ["Spaghetti", "DryStore", "kg"],
  ["Soba Noodles", "DryStore", "kg"],
  ["Rice Noodles (flat)", "DryStore", "kg"],
  ["Egg Noodles", "DryStore", "kg"],
  ["Kidney Beans", "DryStore", "kg"],
  ["Pinto Beans", "DryStore", "kg"],
  ["Nachos / Tortilla Chips", "DryStore", "kg"],
  ["Tortilla (wrap)", "DryStore", "pcs"],
  ["Pita Bread", "DryStore", "pcs"],
  ["French Loaf", "DryStore", "pcs"],
  ["Brown Bread", "DryStore", "pcs"],
  ["Focaccia", "DryStore", "pcs"],
  ["Oats", "DryStore", "kg"],
  ["Peanut Butter", "DryStore", "kg"],
  ["Nutella", "DryStore", "kg"],
  ["Kitkat", "DryStore", "pcs"],
  ["Oreo", "DryStore", "pcs"],
  ["Walnuts", "DryStore", "kg"],
  ["Cashew Nuts", "DryStore", "kg"],
  ["Soya Granules", "DryStore", "kg"],
  ["Lentils (Dal)", "DryStore", "kg"],
  ["Dark Chocolate", "DryStore", "kg"],
  ["Cocoa Powder", "DryStore", "kg"],
  ["Ladyfinger Biscuits", "DryStore", "kg"],
  ["Gelatin / Agar-Agar", "DryStore", "kg"],
  ["Basil Pesto Sauce", "Sauces", "kg"],
  ["Tomato Basil Sauce", "Sauces", "litre"],
  ["Sriracha Sauce", "Sauces", "litre"],
  ["Kimchi Sauce", "Sauces", "litre"],
  ["Thai Red Curry Paste", "Sauces", "kg"],
  ["Miso Paste", "Sauces", "kg"],
  ["Soya Sauce", "Sauces", "litre"],
  ["Harissa", "Sauces", "kg"],
  ["Hummus", "Sauces", "kg"],
  ["Muhammara", "Sauces", "kg"],
  ["Mexican Chili Sauce", "Sauces", "litre"],
  ["Masala Cheese Sauce", "Sauces", "litre"],
  ["Korean Sauce", "Sauces", "litre"],
  ["Wasabi", "Sauces", "kg"],
  ["Olive Oil", "Imported", "litre"],
  ["Coconut Milk", "Imported", "litre"],
  ["Olives (black/green)", "Imported", "kg"],
  ["Sun-dried Tomatoes", "Imported", "kg"],
  ["Togarashi Spice", "Imported", "kg"],
  ["Capers", "Imported", "kg"],
  ["Biscoff", "Imported", "kg"],
  ["Peri Peri Spice Mix", "Spices", "kg"],
  ["Tandoori Spice Mix", "Spices", "kg"],
  ["Hariyali Spice Mix", "Spices", "kg"],
  ["Kadhai Masala", "Spices", "kg"],
  ["Biryani Masala", "Spices", "kg"],
  ["Garam Masala", "Spices", "kg"],
  ["Chaat Masala", "Spices", "kg"],
  ["Apple", "Beverages", "kg"],
  ["Beetroot", "Beverages", "kg"],
  ["Orange", "Beverages", "kg"],
  ["Lemon", "Beverages", "kg"],
  ["Watermelon", "Beverages", "kg"],
  ["Pineapple", "Beverages", "kg"],
  ["Kiwi", "Beverages", "kg"],
  ["Mango", "Beverages", "kg"],
  ["Strawberry", "Beverages", "kg"],
  ["Blueberry", "Beverages", "kg"],
  ["Celery", "Beverages", "kg"],
  ["Mint", "Beverages", "kg"],
  ["Ginger", "Beverages", "kg"],
  ["Parsley", "Beverages", "kg"],
  ["Peach (pulp/fresh)", "Beverages", "kg"],
  ["Passion Fruit Pulp", "Beverages", "litre"],
  ["Guava Pulp", "Beverages", "litre"],
  ["Coconut Water", "Beverages", "litre"],
];

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    .slice(0, 48);
}

export function createMenuIngredientSeed(now: string): MenuIngredient[] {
  return SEED_ROWS.map(([name, category, unit]) => ({
    id: `ing_${slug(name)}`,
    name,
    category,
    unit,
    costPerUnitPaise: 0,
    yieldFactor: 1,
    lastUpdated: now,
    createdAt: now,
  }));
}

export { slug as menuIngredientSlug };
