-- Menu integration seed

alter table if exists recipes add column if not exists menu_category text;
alter table if exists recipes add column if not exists menu_subcategory text;
alter table if exists recipes add column if not exists description text;
alter table if exists recipes add column if not exists selling_price_paise integer;
alter table if exists recipes add column if not exists serving_size text;
alter table if exists recipes add column if not exists is_signature boolean default false;
alter table if exists recipes add column if not exists is_spicy boolean default false;
alter table if exists recipes add column if not exists is_jain_available boolean default true;
alter table if exists recipes add column if not exists is_active boolean default true;
alter table if exists recipes add column if not exists food_cost_target_pct decimal(5,2) default 30.00;

create table if not exists menu_ingredients (
  id text primary key,
  name text not null unique,
  category text not null,
  unit text not null,
  cost_per_unit integer not null default 0,
  yield_factor decimal(4,3) default 1.000,
  last_updated timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists menu_recipe_ingredients (
  id text primary key,
  recipe_id text not null references recipes(id) on delete cascade,
  ingredient_id text not null references menu_ingredients(id),
  quantity decimal(10,3) not null,
  unit text not null,
  notes text,
  yield_factor decimal(4,3) default 1.000,
  created_at timestamptz default now()
);

create table if not exists recipe_cost_snapshots (
  id text primary key,
  recipe_id text not null references recipes(id) on delete cascade,
  ingredient_cost integer not null default 0,
  overhead_pct decimal(5,2) not null default 0,
  packaging_cost integer not null default 0,
  total_cost integer not null default 0,
  selling_price integer not null default 0,
  food_cost_pct decimal(5,2) not null default 0,
  margin integer not null default 0,
  margin_pct decimal(5,2) not null default 0,
  target_pct decimal(5,2) not null default 0,
  status text not null default 'on_target',
  portions integer not null default 1,
  created_at timestamptz default now()
);

insert into menu_ingredients (id, name, category, unit, cost_per_unit, yield_factor, last_updated, created_at)
values
('ing_paneer', 'Paneer', 'Dairy', 'kg', 0, 1.000, now(), now()),
('ing_mozzarella_cheese', 'Mozzarella Cheese', 'Dairy', 'kg', 0, 1.000, now(), now()),
('ing_cream_cheese', 'Cream Cheese', 'Dairy', 'kg', 0, 1.000, now(), now()),
('ing_fresh_cream', 'Fresh Cream', 'Dairy', 'litre', 0, 1.000, now(), now()),
('ing_butter', 'Butter', 'Dairy', 'kg', 0, 1.000, now(), now()),
('ing_curd_hung_curd', 'Curd / Hung Curd', 'Dairy', 'kg', 0, 1.000, now(), now()),
('ing_milk', 'Milk', 'Dairy', 'litre', 0, 1.000, now(), now()),
('ing_parmesan_cheese', 'Parmesan Cheese', 'Dairy', 'kg', 0, 1.000, now(), now()),
('ing_ice_cream', 'Ice Cream', 'Dairy', 'litre', 0, 1.000, now(), now()),
('ing_whipped_cream', 'Whipped Cream', 'Dairy', 'litre', 0, 1.000, now(), now()),
('ing_tomato', 'Tomato', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_onion', 'Onion', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_capsicum_red', 'Capsicum Red', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_capsicum_yellow', 'Capsicum Yellow', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_capsicum_green', 'Capsicum Green', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_zucchini', 'Zucchini', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_broccoli', 'Broccoli', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_mushroom', 'Mushroom', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_baby_corn', 'Baby Corn', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_carrot', 'Carrot', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_spinach', 'Spinach', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_cucumber', 'Cucumber', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_avocado', 'Avocado', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_lettuce', 'Lettuce', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_methi', 'Methi', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_bok_choi', 'Bok Choi', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_water_chestnut', 'Water Chestnut', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_spring_onion', 'Spring Onion', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_jalapenos_pickled', 'Jalapenos (pickled)', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_corn_sweet_corn', 'Corn (sweet corn)', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_potato', 'Potato', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_cauliflower', 'Cauliflower', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_green_beans', 'Green Beans', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_peas', 'Peas', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_cherry_tomatoes', 'Cherry Tomatoes', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_tofu', 'Tofu', 'Vegetables', 'kg', 0, 1.000, now(), now()),
('ing_basmati_rice', 'Basmati Rice', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_jasmine_rice', 'Jasmine Rice', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_penne_pasta', 'Penne Pasta', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_spaghetti', 'Spaghetti', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_soba_noodles', 'Soba Noodles', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_rice_noodles_flat', 'Rice Noodles (flat)', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_egg_noodles', 'Egg Noodles', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_kidney_beans', 'Kidney Beans', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_pinto_beans', 'Pinto Beans', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_nachos_tortilla_chips', 'Nachos / Tortilla Chips', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_tortilla_wrap', 'Tortilla (wrap)', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_pita_bread', 'Pita Bread', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_french_loaf', 'French Loaf', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_brown_bread', 'Brown Bread', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_focaccia', 'Focaccia', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_oats', 'Oats', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_peanut_butter', 'Peanut Butter', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_nutella', 'Nutella', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_kitkat', 'Kitkat', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_oreo', 'Oreo', 'DryStore', 'pcs', 0, 1.000, now(), now()),
('ing_walnuts', 'Walnuts', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_cashew_nuts', 'Cashew Nuts', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_soya_granules', 'Soya Granules', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_lentils_dal', 'Lentils (Dal)', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_dark_chocolate', 'Dark Chocolate', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_cocoa_powder', 'Cocoa Powder', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_ladyfinger_biscuits', 'Ladyfinger Biscuits', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_gelatin_agar_agar', 'Gelatin / Agar-Agar', 'DryStore', 'kg', 0, 1.000, now(), now()),
('ing_basil_pesto_sauce', 'Basil Pesto Sauce', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_tomato_basil_sauce', 'Tomato Basil Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_sriracha_sauce', 'Sriracha Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_kimchi_sauce', 'Kimchi Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_thai_red_curry_paste', 'Thai Red Curry Paste', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_miso_paste', 'Miso Paste', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_soya_sauce', 'Soya Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_harissa', 'Harissa', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_hummus', 'Hummus', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_muhammara', 'Muhammara', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_mexican_chili_sauce', 'Mexican Chili Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_masala_cheese_sauce', 'Masala Cheese Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_korean_sauce', 'Korean Sauce', 'Sauces', 'litre', 0, 1.000, now(), now()),
('ing_wasabi', 'Wasabi', 'Sauces', 'kg', 0, 1.000, now(), now()),
('ing_olive_oil', 'Olive Oil', 'Imported', 'litre', 0, 1.000, now(), now()),
('ing_coconut_milk', 'Coconut Milk', 'Imported', 'litre', 0, 1.000, now(), now()),
('ing_olives_black_green', 'Olives (black/green)', 'Imported', 'kg', 0, 1.000, now(), now()),
('ing_sun_dried_tomatoes', 'Sun-dried Tomatoes', 'Imported', 'kg', 0, 1.000, now(), now()),
('ing_togarashi_spice', 'Togarashi Spice', 'Imported', 'kg', 0, 1.000, now(), now()),
('ing_capers', 'Capers', 'Imported', 'kg', 0, 1.000, now(), now()),
('ing_biscoff', 'Biscoff', 'Imported', 'kg', 0, 1.000, now(), now()),
('ing_peri_peri_spice_mix', 'Peri Peri Spice Mix', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_tandoori_spice_mix', 'Tandoori Spice Mix', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_hariyali_spice_mix', 'Hariyali Spice Mix', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_kadhai_masala', 'Kadhai Masala', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_biryani_masala', 'Biryani Masala', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_garam_masala', 'Garam Masala', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_chaat_masala', 'Chaat Masala', 'Spices', 'kg', 0, 1.000, now(), now()),
('ing_apple', 'Apple', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_beetroot', 'Beetroot', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_orange', 'Orange', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_lemon', 'Lemon', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_watermelon', 'Watermelon', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_pineapple', 'Pineapple', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_kiwi', 'Kiwi', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_mango', 'Mango', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_strawberry', 'Strawberry', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_blueberry', 'Blueberry', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_celery', 'Celery', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_mint', 'Mint', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_ginger', 'Ginger', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_parsley', 'Parsley', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_peach_pulp_fresh', 'Peach (pulp/fresh)', 'Beverages', 'kg', 0, 1.000, now(), now()),
('ing_passion_fruit_pulp', 'Passion Fruit Pulp', 'Beverages', 'litre', 0, 1.000, now(), now()),
('ing_guava_pulp', 'Guava Pulp', 'Beverages', 'litre', 0, 1.000, now(), now()),
('ing_coconut_water', 'Coconut Water', 'Beverages', 'litre', 0, 1.000, now(), now())
on conflict (id) do nothing;

-- Menu recipes (207 items)
-- Note: requires recipes.id to be text; alter if still uuid in your deployment.


-- Seed 207 Table Tales menu recipes (brand-wide, branch_id NULL)
-- Requires recipes.id text PK. Run id migration separately if still uuid.

insert into recipes (
  id, name, selling_price, selling_price_paise, yield, yield_unit, status, outlet, branch_id,
  menu_category, menu_subcategory, description, serving_size,
  is_signature, is_spicy, is_jain_available, is_active, food_cost_target_pct, created_at
) values
  ('rec_abc', 'ABC', 255, 25500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Apple, Beetroot, Carrot & Celery.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_green_goddess', 'Green Goddess', 245, 24500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Cucumber, Celery, Parsley, Spinach & Apple.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_immune_booster', 'Immune Booster', 245, 24500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Orange, Lemon, Ginger with a hint of Pineapple.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_ginger_zinger', 'Ginger Zinger', 245, 24500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Carrot, Lemon, Ginger with a hint of Apple.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_berry_blast', 'Berry Blast', 260, 26000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Beetroot, Strawberry & Blueberry.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_tangy_tropical', 'Tangy Tropical', 255, 25500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Orange, Apple, Pineapple & Mint.', '250 ml', true, false, true, true, 22.00, now()),
  ('rec_orange', 'Orange', 200, 20000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Fresh orange juice.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_nimbu_pani_sweet_salted', 'Nimbu Pani (Sweet/Salted)', 110, 11000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Classic Indian lemonade, sweet or salted.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_watermelon', 'Watermelon', 155, 15500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Fresh watermelon juice.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_pineapple', 'Pineapple', 180, 18000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Fresh pineapple juice.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_apple', 'Apple', 220, 22000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Fresh apple juice.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_kiwi', 'Kiwi', 240, 24000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Cold Pressed Juices', NULL, 'Fresh kiwi juice.', '250 ml', false, false, true, true, 22.00, now()),
  ('rec_nutella_shake', 'Nutella Shake', 260, 26000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Rich Nutella blended milkshake.', '250 ml', true, false, true, true, 28.00, now()),
  ('rec_chocolate_shake', 'Chocolate Shake', 240, 24000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Classic chocolate milkshake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_mix_berry_cheesecake_shake', 'Mix Berry Cheesecake Shake', 290, 29000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Mix berry cheesecake flavoured shake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_choco_brownie_shake', 'Choco Brownie Shake', 260, 26000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Chocolate brownie blended shake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_kitkat_shake', 'Kitkat Shake', 245, 24500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Kitkat blended milkshake.', '250 ml', true, false, true, true, 28.00, now()),
  ('rec_oreo_cookie_shake', 'Oreo Cookie Shake', 245, 24500, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Oreo cookie blended milkshake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_cold_coffee', 'Cold Coffee', 230, 23000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Chilled blended cold coffee.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_caramel_cold_coffee', 'Caramel Cold Coffee', 240, 24000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Cold coffee with caramel.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_mango_shake', 'Mango Shake', 240, 24000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Fresh mango milkshake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_dry_fruit_shake', 'Dry Fruit Shake', 260, 26000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Rich dry fruit blended milkshake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_peanut_butter_oats_protein_shake', 'Peanut Butter & Oats Protein Shake', 290, 29000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Protein-rich peanut butter and oats shake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_fat_burner_shake', 'Fat Burner Shake', 270, 27000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Milkshakes', NULL, 'Fat burner health shake.', '250 ml', false, false, true, true, 28.00, now()),
  ('rec_passion_fizz', 'Passion Fizz', 260, 26000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Passion fruit fizz soda.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_watermelon_mint_mojito', 'Watermelon Mint Mojito', 250, 25000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Watermelon & mint mojito.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_mix_berry_mojito', 'Mix Berry Mojito', 270, 27000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Mix berry mojito.', '250 ml', true, false, true, true, 20.00, now()),
  ('rec_lime_mint_mojito', 'Lime & Mint Mojito', 250, 25000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Classic lime and mint mojito.', '250 ml', true, false, true, true, 20.00, now()),
  ('rec_kiwi_mint_mojito', 'Kiwi Mint Mojito', 260, 26000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Kiwi and mint mojito.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_crazy_banta_soda', 'Crazy Banta Soda', 220, 22000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Crazy banta style soda.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_fresh_lime_soda', 'Fresh Lime Soda', 140, 14000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Fresh lime soda.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_masala_cola', 'Masala Cola', 190, 19000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sodas', NULL, 'Masala spiced cola.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_peach_ice_tea', 'Peach Ice Tea', 170, 17000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Iced Teas', NULL, 'Chilled peach flavoured ice tea.', '250 ml', true, false, true, true, 20.00, now()),
  ('rec_lemon_ice_tea', 'Lemon Ice Tea', 160, 16000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Iced Teas', NULL, 'Classic lemon ice tea.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_passion_fruit_ice_tea', 'Passion Fruit Ice Tea', 170, 17000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Iced Teas', NULL, 'Passion fruit flavoured ice tea.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_mango_ice_tea', 'Mango Ice Tea', 170, 17000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Iced Teas', NULL, 'Mango flavoured ice tea.', '250 ml', false, false, true, true, 20.00, now()),
  ('rec_passion_bull', 'Passion Bull', 290, 29000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Passion fruit fizz.', '200 ml', true, false, true, true, 22.00, now()),
  ('rec_guava_orange_togarashi', 'Guava Orange Togarashi', 280, 28000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Guava, orange with togarashi spice.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_berry_tonic', 'Berry Tonic', 260, 26000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Berry tonic drink.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_kiwi_kiss_slush', 'Kiwi Kiss Slush', 260, 26000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Kiwi slush drink.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_tropical_sunset', 'Tropical Sunset', 290, 29000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Tropical sunset fizz.', '200 ml', true, false, true, true, 22.00, now()),
  ('rec_strawberry_orange_daiquiri', 'Strawberry Orange Daiquiri', 280, 28000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Strawberry orange daiquiri mocktail.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_pina_berry_chill', 'Pina Berry Chill', 280, 28000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Pineapple berry chill drink.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_apple_cinnamon_fizz', 'Apple Cinnamon Fizz', 290, 29000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Apple cinnamon fizz.', '200 ml', true, false, true, true, 22.00, now()),
  ('rec_pineapple_ale', 'Pineapple Ale', 260, 26000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Pineapple ale mocktail.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_elder_mile', 'Elder Mile', 260, 26000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Elderflower mile drink.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_kiwi_sour', 'Kiwi Sour', 280, 28000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Kiwi sour mocktail.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_ginger_melon_tonic', 'Ginger Melon Tonic', 280, 28000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Fantasy Fizz', NULL, 'Ginger melon tonic.', '200 ml', false, false, true, true, 22.00, now()),
  ('rec_tomato_soup', 'Tomato Soup', 225, 22500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Classic comfort soup with freshest tomatoes & cream, served with croutons.', '210 gms', false, false, true, true, 25.00, now()),
  ('rec_tom_yum', 'Tom Yum', 245, 24500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Thai aromatic spices with carrot, zucchini & bokchoy.', '210 gms', false, true, true, true, 25.00, now()),
  ('rec_cheesy_veg', 'Cheesy Veg', 245, 24500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Creamy cheesy soup with zucchini, mushrooms, carrots, green beans & broccoli.', '210 gms', true, false, true, true, 25.00, now()),
  ('rec_hot_sour', 'Hot & Sour', 230, 23000, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Indo-Chinese tangy & spicy soup with fresh cut veggies.', '210 gms', false, true, false, true, 25.00, now()),
  ('rec_minestrone', 'Minestrone', 230, 23000, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Hearty Italian vegetable soup with tomato base, beans & pasta.', '210 gms', false, false, true, true, 25.00, now()),
  ('rec_burmese_khao_suey', 'Burmese Khao Suey', 320, 32000, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Creamy coconut soup with curry spices, boiled noodles, zucchini, broccoli, carrots, mushrooms & water chestnuts.', '210 gms', true, false, true, true, 25.00, now()),
  ('rec_cream_of_mushroom', 'Cream of Mushroom', 245, 24500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Creamy classic soup with freshly sautéed mushrooms.', '210 gms', false, false, true, true, 25.00, now()),
  ('rec_miso', 'Miso', 250, 25000, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Japanese miso umami soup with tofu, carrots & scallions.', '210 gms', false, false, false, true, 25.00, now()),
  ('rec_mexican_bean', 'Mexican Bean', 245, 24500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Tomato based soup with corn, capsicum, jalapenos, kidney beans & tortilla chips.', '210 gms', true, true, true, true, 25.00, now()),
  ('rec_clear_green', 'Clear Green', 230, 23000, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Chinese green fragrant broth with cabbage, carrots, spring onions, green beans & celery.', '210 gms', false, false, true, true, 25.00, now()),
  ('rec_chinese_noodle', 'Chinese Noodle', 245, 24500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Classic chinese soup with sliced veggies & boiled noodles, drizzled with crispy noodles.', '210 gms', true, false, true, true, 25.00, now()),
  ('rec_sweet_corn', 'Sweet Corn', 225, 22500, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Sweet corn & diced veggies in a Chinese twist.', '210 gms', false, false, true, true, 25.00, now()),
  ('rec_spinach_corn', 'Spinach Corn', 230, 23000, 1, '210 gms', 'active', 'Table Tales', NULL, 'Soups', NULL, 'Fresh spinach, corn & a hint of green chilli.', '210 gms', false, false, true, true, 25.00, now()),
  ('rec_fruit_bowl', 'Fruit Bowl', 320, 32000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Salads', NULL, 'A bowl of freshly cut seasonal fruits.', '300 gms', false, false, true, true, 28.00, now()),
  ('rec_caesar_salad', 'Caesar Salad', 330, 33000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Salads', NULL, 'Creamy romaine base with lettuce & olives topped with crunchy croutons & parmesan cheese.', '300 gms', false, false, true, true, 28.00, now()),
  ('rec_greek_salad', 'Greek Salad', 330, 33000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Salads', NULL, 'Bell peppers, olives, crumbled paneer dressed in greek dressing.', '300 gms', false, false, true, true, 28.00, now()),
  ('rec_dahi_ke_kebab', 'Dahi ke Kebab', 390, 39000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Creamy cutlet patties with hung curd, crumbled paneer & aromatic spices. (8 pcs)', '300 gms', true, false, true, true, 30.00, now()),
  ('rec_hara_bhara_kebab', 'Hara Bhara Kebab', 350, 35000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Savoury pan-fried patties loaded with green vegetables & cottage cheese. (8 pcs)', '300 gms', false, false, true, true, 30.00, now()),
  ('rec_bhutte_ke_kebab', 'Bhutte Ke Kebab', 370, 37000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Crispy golden potato corn tikki filled with Indian masalas & cheese. (8 pcs)', '300 gms', false, false, true, true, 30.00, now()),
  ('rec_paneer_tikka', 'Paneer Tikka', 410, 41000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Classic tandoori paneer cubes marinated in signature spice mix, grilled with onions, capsicum & tomatoes. (8 pcs)', '300 gms', false, true, true, true, 30.00, now()),
  ('rec_hariyali_paneer_tikka', 'Hariyali Paneer Tikka', 410, 41000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Tandoori paneer with hariyali spice marinade, grilled with onions, capsicum & tomatoes. (8 pcs)', '300 gms', false, true, true, true, 30.00, now()),
  ('rec_corn_tikki_chaat', 'Corn Tikki Chaat', 380, 38000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Crispy corn potato tikkis on sweet curd with chutneys, papdi sticks & pico de gallo.', '300 gms', false, false, true, true, 30.00, now()),
  ('rec_assorted_tandoor_platter', 'Assorted Tandoor Platter', 520, 52000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Tandoori paneer, hariyali paneer, hariyali broccoli, tandoori momos & hara bhara kebab. (10 pcs)', '300 gms', false, false, true, true, 30.00, now()),
  ('rec_tandoori_potato_cannelloni', 'Tandoori Potato Cannelloni', 410, 41000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Grilled potatoes stuffed with paneer & cheese, with marinated grilled bell peppers, tomatoes & onions. (8 pcs)', '300 gms', true, false, true, true, 30.00, now()),
  ('rec_tandoori_momos', 'Tandoori Momos', 410, 41000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Steamed veg cheese momos marinated in tandoori spice mix, baked in tandoor & finished with cream & spices. (8 pcs)', '300 gms', false, true, true, true, 30.00, now()),
  ('rec_paneer_kathi_roll', 'Paneer Kathi Roll', 310, 31000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Sauteed paneer wrapped in a tortilla with mint chutney, mayo, salad & cheese.', '300 gms', true, false, true, true, 30.00, now()),
  ('rec_tandoori_paneer_wrap', 'Tandoori Paneer Wrap', 320, 32000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Indian', 'Marinated tandoori paneer, flavored mayo, cheese & salad wrapped in a tortilla.', '300 gms', false, true, true, true, 30.00, now()),
  ('rec_cheese_fondue', 'Cheese Fondue', 540, 54000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Cheese fondue with peri peri fries, sautéed broccoli, baby corn, carrots, nachos, veg cheese balls & garlic croutons.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_golden_tuscan_swirls', 'Golden Tuscan Swirls', 420, 42000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Crispy cheese spinach rolls on tomato basil sauce, topped with cheese & baked till golden, with lettuce salad & roasted walnuts.', '300 gms', true, false, true, true, 32.00, now()),
  ('rec_avocado_toast', 'Avocado Toast', 390, 39000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Crispy toast with mashed avocado, pico de gallo, roasted tomato slices & micro greens. (4 pcs)', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_bruschetta', 'Bruschetta', 370, 37000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'French loaf baked with cheese, fresh basil, olives, corn & tomatoes. (6 pcs)', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_loaded_french_fries', 'Loaded French Fries', 295, 29500, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Peri Peri fries topped with masala cheese sauce, pico de gallo, tomato sauce, jalapenos, black olives & creamy sauce.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_fajita_taco_in_chili_sauce', 'Fajita Taco in Chili Sauce', 390, 39000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Soft taco with sautéed fajita vegetables, bean & corn masala, mexican chili sauce, sour cream & fire-roasted salsa. (4 pcs)', '300 gms', true, true, true, true, 32.00, now()),
  ('rec_cheese_pop_taco', 'Cheese Pop Taco', 430, 43000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Tortilla with kidney beans, cheese popper, masala cheese sauce, lettuce & fire roasted salsa. (4 pcs)', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_mexican_grill_quesadillas', 'Mexican Grill Quesadillas', 410, 41000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Tortilla stuffed with bell peppers, onions, jalapenos & special masala beans topped with cheese.', '300 gms', true, true, true, true, 32.00, now()),
  ('rec_crispy_falafel_crostini', 'Crispy Falafel Crostini', 360, 36000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Crispy bread toast with hummus, olives, lettuce & falafel pieces with Lebanese sauce. (6 pcs)', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_lebanese_loaded_french_fries', 'Lebanese Loaded French Fries', 330, 33000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Fries with Lebanese masala, queso, muhammara & hummus, topped with harissa mayo, pico de gallo & pickled veggies.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_loaded_nachos', 'Loaded Nachos', 330, 33000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Nachos with masala cheese sauce, bell peppers, onions, jalapenos, fire roasted salsa, bean masala & sour cream.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_mexican_bean_wrap', 'Mexican Bean Wrap', 310, 31000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Mexican veggies with kidney beans, creamy mexican sauce & cheese in a tortilla.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_lebanese_platter', 'Lebanese Platter', 330, 33000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Global', 'Falafel, pita bread, lavash, carrot & cucumber with hummus, harissa, muhammara, pesto hummus & beetroot hummus.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_sriracha_paneer_crisp', 'Sriracha Paneer Crisp', 420, 42000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Asian', 'Sriracha glazed paneer with onions & bell peppers, topped with crispy spinach.', '300 gms', false, true, true, true, 32.00, now()),
  ('rec_korean_cream_cheese_pull_apart_bun', 'Korean Cream Cheese Pull Apart Bun', 320, 32000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Asian', 'Cream cheese & mozzarella pull apart buns with Korean sauce & fried garlic.', '300 gms', false, false, true, true, 32.00, now()),
  ('rec_chili_corn_water_chestnut_tempura', 'Chili Corn & Water Chestnut Tempura', 350, 35000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Asian', 'Stir fried tempura corn & water chestnut in spicy sauces.', '300 gms', false, true, true, true, 32.00, now()),
  ('rec_paneer_chilly', 'Paneer Chilly', 430, 43000, 1, '300 gms', 'active', 'Table Tales', NULL, 'Appetizers', 'Asian', 'Indo-Chinese crisp paneer cubes with onions & capsicum in hot & tangy semi-dry sauce.', '300 gms', false, true, true, true, 32.00, now()),
  ('rec_avocado_cream_cheese_cucumber_sushi', 'Avocado Cream Cheese Cucumber Sushi', 420, 42000, 1, '8 pcs', 'active', 'Table Tales', NULL, 'Sushi', NULL, 'Avocado, cream cheese, spring onion, cucumber. Served with pickled ginger, soya sauce & wasabi. (8 pcs)', '8 pcs', false, false, true, true, 35.00, now()),
  ('rec_jalapeno_tempura_sour_cream_sushi', 'Jalapeno Tempura Sour Cream Sushi', 450, 45000, 1, '8 pcs', 'active', 'Table Tales', NULL, 'Sushi', NULL, 'Jalapeno tempura, salsa, carrot, spring onion. (8 pcs)', '8 pcs', false, true, true, true, 35.00, now()),
  ('rec_togarashi_katsu_tofu_sushi', 'Togarashi Katsu Tofu Sushi', 470, 47000, 1, '8 pcs', 'active', 'Table Tales', NULL, 'Sushi', NULL, 'Spicy creamy sauce, bread crumbed tofu, chili sauce, togarashi. (8 pcs)', '8 pcs', false, true, true, true, 35.00, now()),
  ('rec_tandoori_paneer_avocado_sushi', 'Tandoori Paneer Avocado Sushi', 450, 45000, 1, '8 pcs', 'active', 'Table Tales', NULL, 'Sushi', NULL, 'Tandoori paneer, avocado, spicy creamy sauce, cucumber. (8 pcs)', '8 pcs', false, false, true, true, 35.00, now()),
  ('rec_forest_dumpling_with_chili_garlic_sauce', 'Forest Dumpling with Chili Garlic Sauce', 420, 42000, 1, '5 pcs', 'active', 'Table Tales', NULL, 'Dim Sum', NULL, 'Green dumpling with scallion, spinach, cabbage, basil on chili garlic sauce. (5 pcs)', '5 pcs', false, true, true, true, 32.00, now()),
  ('rec_spicy_tofu_with_water_chestnut_dumpling', 'Spicy Tofu with Water Chestnut Dumpling', 380, 38000, 1, '5 pcs', 'active', 'Table Tales', NULL, 'Dim Sum', NULL, 'Dumpling with tofu, water chestnut & chili paste. (5 pcs)', '5 pcs', false, true, true, true, 32.00, now()),
  ('rec_crystal_veggie_cheese_dumpling', 'Crystal Veggie & Cheese Dumpling', 380, 38000, 1, '5 pcs', 'active', 'Table Tales', NULL, 'Dim Sum', NULL, 'Veg dumpling with cheese, carrot, cabbage, mushroom & spinach. (5 pcs)', '5 pcs', false, false, true, true, 32.00, now()),
  ('rec_garlic_bread', 'Garlic Bread', 160, 16000, 1, '4 pcs', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'Sliced French loaf buttered with garlic & herbs. (4 pcs)', '4 pcs', false, false, true, true, 28.00, now()),
  ('rec_garlic_bread_with_cheese', 'Garlic Bread with Cheese', 220, 22000, 1, '4 pcs', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'Sliced French loaf topped & baked with cheese, garlic & herbs. (4 pcs)', '4 pcs', false, false, true, true, 28.00, now()),
  ('rec_cheese_chilli_garlic_bread', 'Cheese Chilli Garlic Bread', 230, 23000, 1, '4 pcs', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'French loaf topped & baked with chilli, cheese, garlic & herbs. (4 pcs)', '4 pcs', false, true, true, true, 28.00, now()),
  ('rec_french_fries', 'French Fries', 170, 17000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'Classic salted potato fries.', '250 gms', false, false, true, true, 28.00, now()),
  ('rec_peri_peri_french_fries', 'Peri Peri French Fries', 190, 19000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'Crispy golden fries tossed in a fiery blend of Peri Peri spices.', '250 gms', false, true, true, true, 28.00, now()),
  ('rec_french_fries_with_cheese', 'French Fries with Cheese', 230, 23000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'Classic fries topped with cheesy sauce.', '250 gms', false, false, true, true, 28.00, now()),
  ('rec_cheese_nachos', 'Cheese Nachos', 270, 27000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Small Plates', NULL, 'Nachos topped with cheese sauce.', '250 gms', false, false, true, true, 28.00, now()),
  ('rec_pesto_veggie_sandwich', 'Pesto Veggie Sandwich', 320, 32000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Fresh veggies — onions, tomatoes, capsicum, olives & zucchini sauteed in pesto, layered with cheese.', '250 gms', true, false, true, true, 30.00, now()),
  ('rec_nacho_nacho_sandwich', 'Nacho Nacho Sandwich', 310, 31000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Jalapenos, onions, corn, tomatoes & capsicum with nachos, beans, cheese & mexican sauce toasted between breads.', '250 gms', true, false, true, true, 30.00, now()),
  ('rec_hariyali_tikka_paneer_grill_sandwich', 'Hariyali Tikka Paneer Grill Sandwich', 320, 32000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Marinated & grilled tandoori paneer in hariyali spice mix, flavoured mayo & mint chutney with onions & tomatoes.', '250 gms', false, true, true, true, 30.00, now()),
  ('rec_italian_sandwich', 'Italian Sandwich', 310, 31000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Olives, onions, tomatoes & capsicum in cocktail sauce topped with cheese & basil.', '250 gms', false, false, true, true, 30.00, now()),
  ('rec_cheese_chutney_pesto_sandwich', 'Cheese Chutney Pesto Sandwich', 310, 31000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Signature sandwich with pesto & green chutney topped with cheese.', '250 gms', false, false, true, true, 30.00, now()),
  ('rec_bombay_masala_sandwich', 'Bombay Masala Sandwich', 300, 30000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Street style sandwich with spicy mashed potatoes, onions, tomatoes & capsicum with cheese & chutney.', '250 gms', true, true, true, true, 30.00, now()),
  ('rec_classic_club_sandwich', 'Classic Club Sandwich', 300, 30000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Sandwiches', NULL, 'Classic 3-tier grilled sandwich with fresh tomatoes, cucumber, onions & cheese.', '250 gms', false, false, true, true, 30.00, now()),
  ('rec_margherita_pizza', 'Margherita Pizza', 380, 38000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Traditional pizza with cherry tomatoes, fresh mozzarella & basil.', '10 inches', false, false, true, true, 30.00, now()),
  ('rec_tangy_spicy_pizza', 'Tangy & Spicy Pizza', 450, 45000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Tomatoes, onions, bell peppers, jalapenos, pickled peppers & green chillies.', '10 inches', false, true, true, true, 30.00, now()),
  ('rec_basil_pesto_pizza', 'Basil Pesto Pizza', 470, 47000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Pesto base with tomatoes, onions, olives, jalapenos & capsicum.', '10 inches', false, false, true, true, 30.00, now()),
  ('rec_tandoori_paneer_pizza', 'Tandoori Paneer Pizza', 460, 46000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Tandoori marinated paneer cubes, onions, tomatoes, coriander, spinach & corn.', '10 inches', true, false, true, true, 30.00, now()),
  ('rec_hariyali_paneer_pizza', 'Hariyali Paneer Pizza', 460, 46000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Hariyali marinated paneer, capsicum, coriander, onions & green chillies.', '10 inches', false, false, true, true, 30.00, now()),
  ('rec_veggie_blast_pizza', 'Veggie Blast Pizza', 460, 46000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Onions, tomatoes, capsicum, baby corn, jalapenos, mushrooms, olives, pickled red chillies & basil.', '10 inches', true, false, true, true, 30.00, now()),
  ('rec_classic_hawaiian_pizza', 'Classic Hawaiian Pizza', 440, 44000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Hawaiian classic with pineapple, jalapenos, onions & red chillies.', '10 inches', false, false, true, true, 30.00, now()),
  ('rec_classic_italian_pizza', 'Classic Italian Pizza', 450, 45000, 1, '10 inches', 'active', 'Table Tales', NULL, 'Pizzas', NULL, 'Italian classic with capsicum, olives, jalapenos, basil & baby corn.', '10 inches', false, false, true, true, 30.00, now()),
  ('rec_enchilada_in_mexican_chili_sauce', 'Enchilada in Mexican Chili Sauce', 530, 53000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Mexican', 'Tortilla with beans, fajita vegetables, corn, paneer & Mexican masalas in authentic chili sauce, topped with queso, served with Mexican rice, pico de gallo, sour cream & lettuce.', '400 gms', true, true, true, true, 32.00, now()),
  ('rec_burrito_bowl', 'Burrito Bowl', 440, 44000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Mexican', 'Rice, pinto beans, corn, pico de gallo, salsa, sour cream, fajita vegetables, cheese, lettuce & paneer in Mexican chili sauce, topped with nachos.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_mexican_rice_pot', 'Mexican Rice Pot', 550, 55000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Mexican', 'Rice with sweet corn, bell peppers & kidney beans in tomato gravy with broccoli, zucchini, carrot & baby corn, topped with nachos & cheese.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_lebanese_rice_bowl', 'Lebanese Rice Bowl', 520, 52000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Lebanese', 'Shawarma spiced rice with paneer, crispy sticks, falafel, corn, red paprika, cucumber, tomatoes, lettuce & pickled veggies, topped with hummus, pesto hummus, harissa & toum.', '400 gms', true, false, true, true, 32.00, now()),
  ('rec_pasta_arrabiata', 'Pasta Arrabiata', 390, 39000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Pasta', 'Penne in classic spicy Italian tomato sauce with capsicum, olives, zucchini & red paprika. Served with two garlic breads.', '400 gms', false, true, true, true, 32.00, now()),
  ('rec_penne_roseo', 'Penne Roseo', 420, 42000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Pasta', 'Penne in tomato & cheese sauce with broccoli, zucchini, mushrooms & capsicum, finished with basil & parsley. Served with two garlic breads.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_penne_pesto', 'Penne Pesto', 440, 44000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Pasta', 'Penne in fresh basil pesto sauce with bell peppers, olives, zucchini & mushrooms. Served with two garlic breads.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_spaghetti_alfredo', 'Spaghetti Alfredo', 390, 39000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Pasta', 'Spaghetti in creamy cheese sauce with capsicum, zucchini, mushrooms, cherry tomatoes & olives. Served with two garlic breads.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_bangkok_hawker_style_noodles', 'Bangkok Hawker Style Noodles', 450, 45000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Noodles', 'Thai coconut spicy fragrant noodles with chinese cabbage, carrot, mushroom & trio of bell peppers.', '400 gms', false, true, true, true, 32.00, now()),
  ('rec_pad_thai_noodles', 'Pad Thai Noodles', 420, 42000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Noodles', 'Flat rice noodles with asian sauces, Bok Choi, chinese cabbage, zucchini, trio of bell peppers, carrots, garnished with crushed peanuts.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_chili_soba_noodles', 'Chili Soba Noodles', 430, 43000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Noodles', 'Japanese soba noodles with zucchini, broccoli & red yellow capsicum in chili garlic flavour.', '400 gms', false, true, true, true, 32.00, now()),
  ('rec_ramen_noodles_bowl', 'Ramen Noodles Bowl', 450, 45000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Noodles', 'Japanese miso ramen with fragrant broth, noodles, tofu, bok choi, mushrooms & sweet corn, garnished with spring onions.', '400 gms', false, false, false, true, 32.00, now()),
  ('rec_kimchi_noodles_stir_fry', 'Kimchi Noodles Stir Fry', 420, 42000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Noodles', 'Korean stir fry with kimchi sauce, noodles, sesame, chinese cabbage, bok choi, carrots & capsicum.', '400 gms', false, true, true, true, 32.00, now()),
  ('rec_red_thai_curry_with_jasmine_rice', 'Red Thai Curry with Jasmine Rice', 490, 49000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Curry', 'Coconut Thai red curry with bell peppers, mushroom, zucchini, carrot, bok choi & water chestnut, served with jasmine rice.', '400 gms', false, true, true, true, 32.00, now()),
  ('rec_tofu_rendang_curry_with_jasmine_rice', 'Tofu Rendang Curry with Jasmine Rice', 490, 49000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Curry', 'Spicy tofu & broccoli curry in Malaysian Korean fusion style, served with jasmine rice.', '400 gms', false, true, false, true, 32.00, now()),
  ('rec_steamed_jasmine_rice', 'Steamed Jasmine Rice', 250, 25000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Curry', 'Perfectly steamed aromatic jasmine rice.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_burnt_garlic_corn_fried_rice_with_baby_corn_curr', 'Burnt Garlic Corn Fried Rice with Baby Corn Curry', 450, 45000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Curry', 'Crisp burnt garlic & baby corn fried rice with Chinese curry, sautéed baby corn & bell peppers.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_asian_veggies_in_satay_curry_with_jasmine_rice', 'Asian Veggies in Satay Curry with Jasmine Rice', 490, 49000, 1, '400 gms', 'active', 'Table Tales', NULL, 'Mains', 'Asian Curry', 'Stir fried trio capsicum & zucchini in sweet & spicy Thai peanut sauce, served with jasmine rice.', '400 gms', false, false, true, true, 32.00, now()),
  ('rec_ghughra_naan_platter', 'Ghughra Naan Platter', 550, 55000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Naan stuffed with cheese, capsicum & onions, inspired by Amdavadi gughra sandwich, served with dal makhni, mint chutney, onions & pickle.', '250 gms', true, false, true, true, 30.00, now()),
  ('rec_cheese_naan_platter', 'Cheese Naan Platter', 520, 52000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Cheese stuffed naan served with dal makhni, mint chutney, pickle & onions.', '250 gms', false, false, true, true, 30.00, now()),
  ('rec_cheese_chilli_garlic_naan_platter', 'Cheese Chilli Garlic Naan Platter', 520, 52000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Cheese & chili stuffed naan with minced garlic, served with dal makhni, mint chutney, pickle & onions.', '250 gms', false, true, true, true, 30.00, now()),
  ('rec_paneer_paratha', 'Paneer Paratha', 250, 25000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Indian flatbread stuffed with spiced cottage cheese. Served with raita & pickle.', '250 gms', false, false, true, true, 30.00, now()),
  ('rec_mixed_vegetable_paratha', 'Mixed Vegetable Paratha', 240, 24000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Whole wheat flatbread with carrots, green beans, cauliflower, potato, peas & paneer. Served with raita & pickle.', '250 gms', true, false, true, true, 30.00, now()),
  ('rec_aloo_onion_paratha', 'Aloo Onion Paratha', 230, 23000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Whole wheat flatbread stuffed with onions & mashed potatoes with Indian spices. Served with raita & pickle.', '250 gms', false, false, true, true, 30.00, now()),
  ('rec_cheese_chilli_paratha', 'Cheese Chilli Paratha', 230, 23000, 1, '250 gms', 'active', 'Table Tales', NULL, 'Platters', NULL, 'Melted cheese and spicy chilies in a crispy golden flatbread. Served with raita & pickle.', '250 gms', false, true, true, true, 30.00, now()),
  ('rec_makkhanwala_paneer', 'Makkhanwala Paneer', 490, 49000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Paneer cubes cooked in creamy signature makhni gravy.', '460 gms', true, false, true, true, 32.00, now()),
  ('rec_kadhai_paneer', 'Kadhai Paneer', 480, 48000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Paneer & veggies in rich red and brown gravy with homemade Kadhai masala.', '460 gms', false, false, true, true, 32.00, now()),
  ('rec_desi_paneer_gotalo_with_patti_pav', 'Desi Paneer Gotalo with Patti Pav', 520, 52000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Table Tales speciality — desi tawa crumbled paneer with tangy & spicy gravy, served with 4 pieces of Patti Pav.', '460 gms', true, true, true, true, 32.00, now()),
  ('rec_paneer_tikka_masala', 'Paneer Tikka Masala', 490, 49000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Tandoori paneer in rich red & brown gravy with special tandoori spice mix.', '460 gms', false, true, true, true, 32.00, now()),
  ('rec_paneer_chatpata', 'Paneer Chatpata', 450, 45000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Unique paneer & veggie preparation resembling chaat flavors in tomato gravy with salad on top.', '460 gms', true, false, true, true, 32.00, now()),
  ('rec_lasooni_paneer', 'Lasooni Paneer', 470, 47000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Paneer cubes tossed with minced garlic in rich brown gravy.', '460 gms', false, false, true, true, 32.00, now()),
  ('rec_paneer_do_pyaza', 'Paneer Do Pyaza', 470, 47000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Paneer cubes & two types of onions simmered in rich onion gravy with special masalas.', '460 gms', false, false, true, true, 32.00, now()),
  ('rec_pahadi_paneer_tikka_masala', 'Pahadi Paneer Tikka Masala', 490, 49000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Tandoori paneer marinated in hariyali spice mix served with spiced spinach gravy.', '460 gms', false, false, true, true, 32.00, now()),
  ('rec_veg_shahi_korma', 'Veg Shahi Korma', 470, 47000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Vegetable', 'Carrots, green beans, peas & cauliflower in rich brown gravy, handi style.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_hariyali_broccoli', 'Hariyali Broccoli', 410, 41000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Vegetable', 'Marinated & tandoori broccoli on creamy tomato & spice-infused brown gravy.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_desi_videsi', 'Desi Videsi', 480, 48000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Vegetable', 'Local veggies — peas, carrots, green beans, bell peppers — with zucchini, mushroom, corn & broccoli in a fragrant gravy.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_veg_hyderabadi', 'Veg Hyderabadi', 460, 46000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Vegetable', 'Green beans, carrots, cauliflower, american corn, peas, capsicum & onions in special spiced green gravy.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_subz_tirangi', 'Subz Tirangi', 570, 57000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Vegetable', 'Vegetables in three distinct gravies: red, green & white cashew gravy.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_methi_matar_malai', 'Methi Matar Malai', 450, 45000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Vegetable', 'Creamy white gravy with peas & methi.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_soya_kheema_with_patti_pav', 'Soya Kheema with Patti Pav', 495, 49500, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Kofta', 'Soft soya granules in fragrant gravy with masalas, served with four patti pav.', '460 gms', false, false, true, true, 30.00, now()),
  ('rec_paneer_tirangi', 'Paneer Tirangi', 590, 59000, 1, '460 gms', 'active', 'Table Tales', NULL, 'Punjabi Mains', 'Paneer', 'Paneer in three distinct gravies: red, green & white cashew gravy.', '460 gms', false, false, true, true, 32.00, now()),
  ('rec_veg_dum_biryani', 'Veg Dum Biryani', 460, 46000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Traditional slow-cooked biryani with rice, paneer, vegetables, aromatic spices & makhmali gravy.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_the_og_hyderabadi_biryani', 'The OG Hyderabadi Biryani', 460, 46000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Authentic biryani layered with rice, potatoes, carrots & cauliflower, baked with housemade biryani masala, phudina & crispy onions.', '450 gms', true, false, true, true, 28.00, now()),
  ('rec_madras_rice', 'Madras Rice', 460, 46000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Aromatic rice with mushrooms, bell peppers, zucchini & carrots, with curry leaves tadka & a hint of coconut.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_masala_khichdi', 'Masala Khichdi', 410, 41000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Aromatic rice & lentils slow cooked with carrots, peas & tomatoes finished with mild spices & ghee.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_palak_khichdi', 'Palak Khichdi', 430, 43000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Spinach khichdi cooked with veggies, finished with mild spices, garlic & ghee.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_veg_pulao', 'Veg Pulao', 350, 35000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Mixed vegetables cooked with fragrant basmati rice & special spices.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_jeera_rice', 'Jeera Rice', 270, 27000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Aromatic basmati rice with ghee & cumin seeds, coriander drizzled on top.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_steamed_rice', 'Steamed Rice', 230, 23000, 1, '450 gms', 'active', 'Table Tales', NULL, 'Indian Rice', NULL, 'Basmati rice boiled to perfection.', '450 gms', false, false, true, true, 28.00, now()),
  ('rec_plain_roti', 'Plain Roti', 60, 6000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Classic plain roti.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_butter_roti', 'Butter Roti', 75, 7500, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Classic roti with butter.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_garlic_coriander_roti', 'Garlic Coriander Roti', 130, 13000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Roti with garlic and coriander.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_plain_naan', 'Plain Naan', 95, 9500, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Classic plain naan.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_butter_naan', 'Butter Naan', 115, 11500, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Classic naan with butter.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_garlic_naan', 'Garlic Naan', 120, 12000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Naan with garlic.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_hariyali_garlic_naan', 'Hariyali Garlic Naan', 160, 16000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Hariyali spiced garlic naan.', '50 gms', true, false, true, true, 20.00, now()),
  ('rec_chatpata_naan', 'Chatpata Naan', 130, 13000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Chatpata spiced naan.', '50 gms', true, false, true, true, 20.00, now()),
  ('rec_pesto_olive_cheese_naan', 'Pesto Olive Cheese Naan', 195, 19500, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Naan with pesto, olive & cheese.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_jalapeno_cream_cheese_naan', 'Jalapeno Cream Cheese Naan', 210, 21000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Naan with jalapeno & cream cheese.', '50 gms', true, true, true, true, 20.00, now()),
  ('rec_mint_makhni_cheese_naan', 'Mint Makhni Cheese Naan', 210, 21000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Naan with mint, makhni butter & cheese.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_cheese_naan', 'Cheese Naan', 190, 19000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Cheese stuffed naan.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_cheese_garlic_naan', 'Cheese Garlic Naan', 195, 19500, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Cheese & garlic naan.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_mughlai_roti', 'Mughlai Roti', 190, 19000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Classic mughlai style roti.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_lachha_paratha', 'Lachha Paratha', 140, 14000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Layered crispy paratha.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_kulcha', 'Kulcha', 140, 14000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Classic kulcha bread.', '50 gms', false, false, true, true, 20.00, now()),
  ('rec_patti_pav_4_pcs', 'Patti Pav (4 pcs)', 70, 7000, 1, '4 pcs', 'active', 'Table Tales', NULL, 'Breads', NULL, 'Four pieces of patti pav.', '4 pcs', false, false, true, true, 20.00, now()),
  ('rec_chaas', 'Chaas', 100, 10000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Classic Indian buttermilk.', '250 ml', false, false, true, true, 18.00, now()),
  ('rec_masala_chaas', 'Masala Chaas', 110, 11000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Spiced Indian buttermilk.', '250 ml', false, false, true, true, 18.00, now()),
  ('rec_masala_papad', 'Masala Papad', 90, 9000, 1, '1 pc', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Masala topped papad.', '1 pc', false, false, true, true, 18.00, now()),
  ('rec_roasted_papad', 'Roasted Papad', 45, 4500, 1, '1 pc', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Roasted papad.', '1 pc', false, false, true, true, 18.00, now()),
  ('rec_fried_papad', 'Fried Papad', 50, 5000, 1, '1 pc', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Fried papad.', '1 pc', false, false, true, true, 18.00, now()),
  ('rec_raita', 'Raita', 120, 12000, 1, '120 gms', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Tomato Onion / Cucumber / Pineapple Raita.', '120 gms', false, false, true, true, 18.00, now()),
  ('rec_plain_curd', 'Plain Curd', 70, 7000, 1, '120 gms', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Plain fresh curd.', '120 gms', false, false, true, true, 18.00, now()),
  ('rec_sweet_lassi', 'Sweet Lassi', 200, 20000, 1, '250 ml', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Classic sweet lassi.', '250 ml', false, false, true, true, 18.00, now()),
  ('rec_sour_cream', 'Sour Cream', 80, 8000, 1, '50 gms', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Housemade sour cream.', '50 gms', false, false, true, true, 18.00, now()),
  ('rec_green_salad', 'Green Salad', 140, 14000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Fresh green salad.', '100 gms', false, false, true, true, 18.00, now()),
  ('rec_kachumber', 'Kachumber', 130, 13000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Sides', NULL, 'Classic Indian kachumber salad.', '100 gms', false, false, true, true, 18.00, now()),
  ('rec_berry_cheesecake', 'Berry Cheesecake', 330, 33000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Housemade berry cheesecake.', '100 gms', true, false, true, true, 25.00, now()),
  ('rec_brownie_with_ice_cream', 'Brownie with Ice Cream', 290, 29000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Warm brownie served with ice cream.', '100 gms', false, false, true, true, 25.00, now()),
  ('rec_rabdi_gulab_jamun', 'Rabdi Gulab Jamun', 370, 37000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Classic gulab jamun with rabdi.', '100 gms', true, false, true, true, 25.00, now()),
  ('rec_tiramisu', 'Tiramisu', 330, 33000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Classic Italian tiramisu.', '100 gms', true, false, true, true, 25.00, now()),
  ('rec_chocolate_truffle_ball_and_mousse', 'Chocolate Truffle Ball and Mousse', 320, 32000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Chocolate truffle ball with mousse.', '100 gms', false, false, true, true, 25.00, now()),
  ('rec_chocolate_fondue', 'Chocolate Fondue', 330, 33000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Chocolate fondue served with seasonal fruit, cookies & sponge cake pieces.', '100 gms', false, false, true, true, 25.00, now()),
  ('rec_hot_chocolate', 'Hot Chocolate', 240, 24000, 1, '200 ml', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Classic hot chocolate with whipped cream & biscoff on top.', '200 ml', false, false, true, true, 25.00, now()),
  ('rec_ice_cream_sundae', 'Ice Cream Sundae', 350, 35000, 1, '100 gms', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Ice cream sundae — Mango / Chocolate / Vanilla.', '100 gms', false, false, true, true, 25.00, now()),
  ('rec_ice_cream_scoop', 'Ice Cream Scoop', 100, 10000, 1, '1 scoop', 'active', 'Table Tales', NULL, 'Desserts', NULL, 'Single scoop — Chocolate / Vanilla / Mango / Kesar Pista / Coffee.', '1 scoop', false, false, true, true, 25.00, now())
on conflict (id) do nothing;
